// Weekly Update System Types for Adam Halls Garden Center

export interface WeeklyMetrics {
  weekStart: string; // ISO date string
  weekEnd: string; // ISO date string
  weekNumber: number;
  year: number;
  
  // Sales Metrics
  sales: {
    totalRevenue: number;
    totalOrders: number;
    averageOrderValue: number;
    topSellingProducts: TopProduct[];
    salesByCategory: CategorySales[];
    newCustomers: number;
    returningCustomers: number;
  };
  
  // Inventory Metrics
  inventory: {
    totalProducts: number;
    newProducts: number;
    outOfStock: number;
    lowStock: number;
    inventoryValue: number;
    topPerformingCategories: CategoryPerformance[];
    seasonalTrends: SeasonalTrend[];
  };
  
  // Customer Metrics
  customers: {
    totalCustomers: number;
    newCustomers: number;
    customerSatisfaction: number;
    topCustomerFeedback: CustomerFeedback[];
    customerInquiries: number;
    serviceRequests: number;
  };
  
  // Operations Metrics
  operations: {
    staffHours: number;
    maintenanceTasks: number;
    completedTasks: number;
    pendingTasks: number;
    equipmentIssues: number;
    supplyOrders: number;
  };
  
  // Marketing Metrics
  marketing: {
    socialMediaPosts: number;
    emailCampaigns: number;
    websiteVisits: number;
    promotionalOffers: number;
    eventAttendance: number;
    advertisingSpend: number;
  };
  
  // Financial Metrics
  financial: {
    grossProfit: number;
    netProfit: number;
    expenses: number;
    payroll: number;
    utilities: number;
    supplies: number;
    marketing: number;
    other: number;
  };
  
  // Weather Impact
  weather: {
    averageTemperature: number;
    rainfall: number;
    sunnyDays: number;
    impactOnSales: string;
    seasonalNotes: string;
  };
  
  // Notes and Observations
  notes: {
    highlights: string[];
    challenges: string[];
    opportunities: string[];
    actionItems: ActionItem[];
    nextWeekGoals: string[];
  };
  
  // Generated by
  generatedBy: string;
  generatedAt: string;
  lastUpdated: string;
}

export interface TopProduct {
  productId: number;
  name: string;
  category: string;
  unitsSold: number;
  revenue: number;
  previousWeekRank: number;
  change: 'up' | 'down' | 'stable';
}

export interface CategorySales {
  category: string;
  revenue: number;
  unitsSold: number;
  percentageOfTotal: number;
  previousWeek: number;
  change: number;
}

export interface CategoryPerformance {
  category: string;
  revenue: number;
  unitsSold: number;
  profitMargin: number;
  inventoryTurnover: number;
  customerInterest: number;
}

export interface SeasonalTrend {
  category: string;
  trend: 'increasing' | 'decreasing' | 'stable';
  reason: string;
  expectedDuration: string;
  recommendations: string[];
}

export interface CustomerFeedback {
  customerId: string;
  rating: number;
  comment: string;
  category: 'product' | 'service' | 'experience';
  date: string;
  resolved: boolean;
}

export interface ActionItem {
  id: string;
  description: string;
  assignedTo: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  dueDate: string;
  status: 'pending' | 'in-progress' | 'completed';
  notes: string;
}

export interface WeeklyUpdateSummary {
  weekNumber: number;
  year: number;
  keyHighlights: string[];
  keyChallenges: string[];
  revenueGrowth: number;
  customerGrowth: number;
  topPerformingProduct: string;
  needsAttention: string[];
}

export interface WeeklyUpdateFilters {
  startDate?: string;
  endDate?: string;
  categories?: string[];
  metrics?: string[];
  includeDetails?: boolean;
}

export interface WeeklyComparison {
  currentWeek: WeeklyMetrics;
  previousWeek: WeeklyMetrics;
  changes: {
    revenue: number;
    orders: number;
    customers: number;
    inventory: number;
    profit: number;
  };
  trends: {
    revenue: 'up' | 'down' | 'stable';
    orders: 'up' | 'down' | 'stable';
    customers: 'up' | 'down' | 'stable';
    inventory: 'up' | 'down' | 'stable';
    profit: 'up' | 'down' | 'stable';
  };
}
